server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: sufi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: "change-this-secret-in-prod-please-32chars"
    expiration-ms: 86400000
  commission:
    default-percent: 10
  admin:
    username: admin
    password: admin123
